### ISSUE TITLE
The images aren't loading in any browser

### ISSUE THREAD

**Issue by apricotisadev** [proximasan/parrotzone.github.io#6]
I have tried a lot of times clearing cache, reloading, trying in different browsers, but it gives the same output
![image](https://github.com/user-attachments/assets/8f21f878-83fc-4560-942c-f4faf596114a)

Here is the result of Inspecting Element
![image](https://github.com/user-attachments/assets/584e479d-00f2-49fe-9585-d6f8134bce02)

**Comment by proximasan** [comment]
oof yeah something must have broken. thanks for notifying, will look into it. in the meantime there's still the offline version tho: https://github.com/proximasan/sdxl_artist_styles_studies

**Comment by titan-rocky** [comment]
Thanks for the reply (that's my alt account 😅)

**Comment by proximasan** [comment]
ok it should be fixed now, actually wasn't too complicated 🫡
